### ISSUE TITLE
variable expansion

### ISSUE THREAD

**Issue by logemann** [dfranssen/docker-keycloak-import-realm#1]
Does this dockerfile really work? According to docs and my test, the variable expansion at
CMD ["-b", "0.0.0.0", "-Dkeycloak.import=/opt/jboss/keycloak/${KEYCLOAK_IMPORT_REALM}"]

shouldnt work. ${KEYCLOAK_IMPORT_REALM} wont get resolved because of the array definition of CMD.

**Comment by spanierm42** [comment]
Yes, this does not work for me either. You do not have variable expansion in the `CMD` part, cf. https://stackoverflow.com/questions/33935807/how-to-define-a-variable-in-a-dockerfile and https://github.com/moby/moby/issues/5509.
Since I currently do not need to change the import, I use a hard-coded one. Maybe that will change later and I will write a solution for that here.

**Comment by dfranssen** [comment]
Sorry for the late reply.

I'm not sure if this image is still relevant.

In current projects I'm using the official keycloak docker image and I'm managing import/export via a mapped volume and by choosing the import/export `command` in the docker-compose.yml:

```
keycloak:
    image: jboss/keycloak:3.4.3.Final
    networks:
      test:
        aliases:
        - keycloak
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_USER=administrator
      - KEYCLOAK_PASSWORD=test
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=test
      - POSTGRES_PORT_5432_TCP_ADDR=keycloak-db
    depends_on:
      - keycloak-db
    #command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test
    command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
      - ./setup:/tmp/keycloak/test/
```

Let me know if this github project is still useful, so I will look into this issue.

**Comment by logemann** [comment]
you dont need to look into it as far as i am concerned. Thanks.

**Comment by spanierm42** [comment]
I am also fine with it. Thanks for the `docker-compose.yml` example.

**Comment by SimonReds** [comment]
Sorry for my "new year" question, but I cannot manage to make it works... Probably it is my problem since I am a complete docker newbie so any help will be greatly appreciated. Thanks!

**Comment by dfranssen** [comment]
Hi,

Have you seen my comment with the import/export command? So this docker image is not used anymore.

In case it is not clear, provide your config and I’m glad to help you out.

Kind regards & Happy NY 😊
Dirk

**Comment by SimonReds** [comment]
Thank you for your fast reply! I have read the comment about the docker image and I have seen that you are now using a new method to import the realm configuration, as reported in your sample yaml file. I modified it just for test purpose:

```
keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    #command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test
    command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
      - ./setup:/tmp/keycloak/test/
```
If I am not wrong the container should read the `import-realm.yaml` (or another name) from the local host directory `./setup`, which is mapped to `/tmp/keycloak/temp`, and then perform the import.
When I lunch the `docker-compose -f keycloak.yml up` I see that it starts creating the container but then it exit with error code 1 and no container is created.

Best Regards,
Simon.
